train_data_path: 'data/remove_strange_values/train.csv'
test_data_path: 'data/remove_strange_values/test.csv'
val_data_path: 'data/remove_strange_values/val.csv'
data_type: "SMILES"
target: "Permeability"
max_len: 250
augmentation: False
augmentation_ratio: 0.5
load_vocab: True
vocab_path: '../data/vocab.pkl'
use_HELM: False